apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: "{{ .Values.spec.namespace }}"
  labels:
    app.kubernetes.io/name: httpbin
spec:
  template:
    spec:
      containers:
        - name: httpbin
          image: mccutchen/go-httpbin
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status/200
              port: http
          readinessProbe:
            httpGet:
              path: /status/200
              port: http
          resources: {}
