apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: "{{ .Values.spec.namespace }}"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    labels: httpbin
  type: LoadBalancer
