apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.spec.appName }}"
  namespace: "{{ .Values.spec.namespace }}"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.spec.appName }}.{{ .Values.spec.domain }}"
    external-dns.alpha.kubernetes.io/ttl: "60"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: "{{ .Values.spec.appName }}"
  type: LoadBalancer
